#!/bin/bash

RED=$(printf '\033[0;31m')
CLEAR=$(printf '\033[0m')

# Find all files to be committed
readarray -d '' changes -u <(git diff -z --staged --name-only)
# Run spotless apply on changed files
./gradlew spotlessApply "${changes[@]}"

status=$?

if [ "$status" = 0 ]; then
    echo "Static analysis succeeded. Updating commit."
    git add "${changes[@]}"
else
    echo "${RED}-------------------------------------------"
    echo       "Spotless exited with nonzero status.       "
    echo       "Please fix all violations before committing"
    echo       "-------------------------------------------${CLEAR}"
fi

exit $status

